@Host = http://localhost:5004
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoic3VwZXJhZG1pbkBleGFtcGxlLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiYzU3M2NjZWUtMmRjNi00OTI2LWI1ZGEtY2MxM2RmOTRkNTg0IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJleHAiOjE3NzgwOTk5MjksImlzcyI6Ikludm9pY2VTeXN0ZW0iLCJhdWQiOiJJbnZvaWNlU3lzdGVtIn0.JKa5n7x4zKZ-6LzsjT1Ivew2CH7vT4pd4Z_yJzYtgSQ

### --- AUTHENTICATION ---

# @name Register
POST {{Host}}/api/auth/register
Content-Type: application/json

{
    "fullName": "akheel",
    "email": "akheel@example.com",
    "password": "akh@123"
}

###

# @name Login
POST {{Host}}/api/auth/login
Content-Type: application/json

{
    "email": "superadmin@example.com",
    "password": "Password123!"
}

###

# @name RefreshToken
POST {{Host}}/api/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "PASTE_REFRESH_TOKEN_HERE"
}

### --- USER MANAGEMENT (Admin Only) ---

# @name GetAllUsers
GET {{Host}}/api/users
Authorization: Bearer {{Token}}

###

# @name GetUserById
GET {{Host}}/api/users/ad3f65de-c7b0-4201-aeba-e974241fa625
Authorization: Bearer {{Token}}

###

# @name UpdateUser
PUT {{Host}}/api/users/ad3f65de-c7b0-4201-aeba-e974241fa625
Authorization: Bearer {{Token}}
Content-Type: application/json

{
    "fullName": "Akheel",
    "roles": ["Accountant"]
}

###

# @name DeleteUser
DELETE {{Host}}/api/users/a8d3753c-ba79-4a02-8180-2937d521cb55
Authorization: Bearer {{Token}}

### --- ROLES & PERMISSIONS ---

# @name GetRoles
GET {{Host}}/api/roles
Authorization: Bearer {{Token}}

###

# @name AssignPermissions
POST {{Host}}/api/roles/PASTE_ROLE_ID_HERE/permissions
Authorization: Bearer {{Token}}
Content-Type: application/json

[
    "PASTE_PERMISSION_ID_1",
    "PASTE_PERMISSION_ID_2"
]
