@WebAPI_HostAddress = http://localhost:5004

POST {{WebAPI_HostAddress}}/api/auth/register
Content-Type: application/json

{
    "name": "akheel",
    "email": "akheel@example.com",
    "password": "akheel123"
}

###

POST {{WebAPI_HostAddress}}/api/auth/login
Content-Type: application/json

{
    "email": "akheel@example.com",
    "password": "akheel123"
}

###

POST {{WebAPI_HostAddress}}/api/auth/refresh
Content-Type: application/json

{
    "refreshToken": "0LkkfT4JPceNXFeqxcn1Yuvl4CpRundvTTRYTNuJvlTH1jB4wfV8DxpKFf/GGSmlbQn166QMQ6wxDV6GnXc0Yw=="
}
