<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Core\InvoiceSystem.Invoicing.Core.csproj" />
    <ProjectReference Include="..\Application\InvoiceSystem.Invoicing.Application.csproj" />
    <ProjectReference Include="..\..\Reporting\Application\InvoiceSystem.Reporting.Application.csproj" />
    <ProjectReference Include="..\..\Clients\Core\InvoiceSystem.Clients.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.5" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
